### ISSUE TITLE
on-timeout is silently ignored

### ISSUE THREAD

**Issue by shadowlmd** [yrutschle/sslh#253]
I just noticed that on-timeout config value is silently ignored in latest SSLH build.

**Comment by shadowlmd** [comment]
I actually fixed it by replacing `on-timeout` with `on_timeout` both in `sslhconf.cfg` and my `sslh.conf`. I couldn't figure how the config parser works, too complicated code.

**Comment by yrutschle** [comment]
Yes, the parser is a bit abstract :-)
I think I dropped the requirement for settings containing dashes at some point -- I'll try and have a look.

**Comment by yrutschle** [comment]
Actually the configuration looks fine to me: on_timeout in the config file, but on-timeout on the command line, which I think is the accepted standard. OTOH as you found out the timeout_protocol() function was in fact using an obsolete variable... I just pushed a fix for that.
Please re-open if I missed something...

**Comment by shadowlmd** [comment]
I don't see an option to re-open the issue. Anyway, your patch does not fix it because parser completely ignores value of `on-timeout` config option. I had to change it to `on_timeout` both in `sslh.conf` and `sshlconf.cfg`, re-run conf2struct and recompile SSLH to make it get parsed.

**Comment by yrutschle** [comment]
I can see the value change with -v4 when specified on the command line:
```
$ ./sslh-fork -v 4 --on-timeout whatever --ssh localhost:22 --tls localhost:443 --listen localhost:4444
verbose: 4
[...]
syslog_facility: auth
on_timeout: whatever
listen [1]:
    host: localhost [...]
```
and same when changing the config file. what do you do?

**Comment by shadowlmd** [comment]
shadowlmd@home:~/git/sslh$ ./sslh-fork --verbose=2 -F/opt/sslh/etc/sslh.cfg
tls addr: 127.0.0.1:24553. libwrap service: (null) log_level: 1 family 2 2 [] []
anyprot addr: 192.168.1.2:24554. libwrap service: (null) log_level: 1 family 2 2 [] []
listening on:
        0.0.0.0:24554   []
        :::24554        []
timeout: 2
**on-timeout: tls**
listening to 2 addresses
0.0.0.0:24554:bind: Address already in use
shadowlmd@home:~/git/sslh$ grep on-timeout /opt/sslh/etc/sslh.cfg
on-timeout: "anyprot";
shadowlmd@home:~/git/sslh$ grep anyprot /opt/sslh/etc/sslh.cfg
     { name: "anyprot"; host: "192.168.1.2"; port: "24554"; }
**on-timeout: "anyprot";**

**Comment by shadowlmd** [comment]
```
shadowlmd@home:~/git/sslh$ sudo sed -i 's/on-timeout/on_timeout/' /opt/sslh/etc/sslh.cfg sslhconf.cfg
shadowlmd@home:~/git/sslh$ make
conf2struct sslhconf.cfg
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-conf.c
cc -Wall -g   -o sslh-fork sslh-fork.o sslh-conf.o common.o sslh-main.o probe.o tls.o argtable3.o  -lpcreposix -lconfig
#strip sslh-fork
cc -Wall -g   -o sslh-select sslh-select.o sslh-conf.o common.o sslh-main.o probe.o tls.o argtable3.o  -lpcreposix -lconfig
#strip sslh-select
cc -Wall -g   -o echosrv echosrv.o probe.o common.o tls.o  -lpcreposix -lconfig
shadowlmd@home:~/git/sslh$ ./sslh-fork --verbose=2 -F/opt/sslh/etc/sslh.cfg
tls addr: 127.0.0.1:24553. libwrap service: (null) log_level: 1 family 2 2 [] []
anyprot addr: 192.168.1.2:24554. libwrap service: (null) log_level: 1 family 2 2 [] []
listening on:
        0.0.0.0:24554   []
        :::24554        []
timeout: 2
on-timeout: anyprot
listening to 2 addresses
0.0.0.0:24554:bind: Address already in use
```

**Comment by yrutschle** [comment]
The setting in the config file should use an underscore, as in test.cfg:
on_timeout: anyprot;

If libconfig supports setting names with dashes, i suppose it'd be more robust to accept both indifferently.

**Comment by yrutschle** [comment]
I pushed a change in `conf2struct` to accept both dashes and underscores in the configuration file.

I realise maybe I should push sslh-conf.c to this repo so people who don't touch the configuration can build without a need for conf2struct.

**Comment by shadowlmd** [comment]
> The setting in the config file should use an underscore, as in test.cfg:
> on_timeout: anyprot;
> 
> If libconfig supports setting names with dashes, i suppose it'd be more robust to accept both indifferently.

In this case you should probably update example.cfg ;)
```
shadowlmd@home:~/git/sslh$ grep on-timeout example.cfg
on-timeout: "timeout";
```

**Comment by shadowlmd** [comment]
> I pushed a change in `conf2struct` to accept both dashes and underscores in the configuration file.
I can confirm it works now with both dash and underscore variant. Thanks! :)

**Comment by yrutschle** [comment]
Ah, I forgot example.cfg. ah well, it'll work now! Thanks for the report, anyways.

**Comment by shadowlmd** [comment]
I just noticed that when sslh is built with sslh-conf.c/sslh-conf.h you have pushed to repository, the problem is back, on-timeout parameter in config is ignored. If delete sslh-conf.c/sslh-conf.h and let conf2struct regenerate them, everything works fine.

**Comment by yrutschle** [comment]
Indeed -- I updated, tagged a new c2s version and updated the version requirement in sslh while I was at it.
Thanks for the feedback!
